{
 "title": "EKS resource cost",
 "tags": [
  "EKS",
  "AWS",
  "Cost"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "cost_service" },
   { "name": "region", "query": "cost_region" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total current month",
   "type": "singlestat",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 1 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(cost_account_month)", "legendFormat": "day_of_month()" }
   ]
  },
  {
   "title": "Last Day cost ",
   "type": "singlestat",
   "description": "Show all aws cost of last day",
   "gridPos": { "h": 15, "w": 5, "x": 5, "y": 1 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(cost_all)", "legendFormat": "daily cost (last day)" }
   ]
  },
  {
   "title": "Month cost by account",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 15, "w": 7, "x": 10, "y": 1 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    { "expr": "cost_account_month", "legendFormat": "{{ description }}" }
   ]
  },
  {
   "title": "Month cost by region",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 1 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    { "expr": "cost_region_month", "legendFormat": "{{ region }}" },
    {
     "expr": "sum(cost_account_month) - sum(cost_region_month)",
     "legendFormat": "not region "
    }
   ]
  },
  { "title": "Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Daily cost regions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(cost_region{service=\"all\"}) by (region)",
     "legendFormat": "{{ region }}"
    },
    {
     "expr": "sum(sum(cost_region{service=\"all\"}) by (region))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Daily cost region by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(cost_service{region=\"$region\"}) by (service)",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "sum(cost_service{region=\"$region\"})",
     "legendFormat": "all $region"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Daily cost services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(cost_service{region=\"all\"}) by (service)",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "sum(sum(cost_service{region=\"all\"}) by (service))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Daily cost service by region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(cost_region{service=\"$service\"}) by (region)",
     "legendFormat": "{{ region }}"
    },
    {
     "expr": "sum(cost_region{service=\"$service\"})",
     "legendFormat": "all $service"
    }
   ]
  }
 ]
}